// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOuR3Q5BCOwJKeDxcs7X2eL3yl_uQOzWU',
    appId: '1:640878965353:web:800fb53d8768b6db4f68f8',
    messagingSenderId: '640878965353',
    projectId: 'auracare-app',
    authDomain: 'auracare-app.firebaseapp.com',
    storageBucket: 'auracare-app.firebasestorage.app',
    measurementId: 'G-ECZNVJJLLT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCC1GBAjNAVxObic21xhxkmly5yoGRNDfg',
    appId: '1:640878965353:android:bfbe1a8deb514caa4f68f8',
    messagingSenderId: '640878965353',
    projectId: 'auracare-app',
    storageBucket: 'auracare-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJEtL4ct4tTUIi42gXLnDJAJc9lwm4fmQ',
    appId: '1:640878965353:ios:f8c3ad30108e680b4f68f8',
    messagingSenderId: '640878965353',
    projectId: 'auracare-app',
    storageBucket: 'auracare-app.firebasestorage.app',
    androidClientId: '640878965353-mmtk8r8ohoraactjqrvavvve52qjh59f.apps.googleusercontent.com',
    iosClientId: '640878965353-51dpe2lrd4aeimaj2em6i3i108amsmi4.apps.googleusercontent.com',
    iosBundleId: 'com.example.auracareApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJEtL4ct4tTUIi42gXLnDJAJc9lwm4fmQ',
    appId: '1:640878965353:ios:f8c3ad30108e680b4f68f8',
    messagingSenderId: '640878965353',
    projectId: 'auracare-app',
    storageBucket: 'auracare-app.firebasestorage.app',
    androidClientId: '640878965353-mmtk8r8ohoraactjqrvavvve52qjh59f.apps.googleusercontent.com',
    iosClientId: '640878965353-51dpe2lrd4aeimaj2em6i3i108amsmi4.apps.googleusercontent.com',
    iosBundleId: 'com.example.auracareApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDOuR3Q5BCOwJKeDxcs7X2eL3yl_uQOzWU',
    appId: '1:640878965353:web:146aaf660b17e7604f68f8',
    messagingSenderId: '640878965353',
    projectId: 'auracare-app',
    authDomain: 'auracare-app.firebaseapp.com',
    storageBucket: 'auracare-app.firebasestorage.app',
    measurementId: 'G-3XCQQ8E4PQ',
  );
}
